// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVtm5SCNv1YurlyQ7A1IMyRHYu26OZ4kk',
    appId: '1:86067174660:web:f2176abab909acd6584451',
    messagingSenderId: '86067174660',
    projectId: 'project-chat-d6cb6',
    authDomain: 'project-chat-d6cb6.firebaseapp.com',
    storageBucket: 'project-chat-d6cb6.appspot.com',
    measurementId: 'G-R6NXN292P0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARgQbiZLaTA9_cITpYcqhYXTQd0bkkMaU',
    appId: '1:86067174660:android:21ddd3f9d8a4dd8d584451',
    messagingSenderId: '86067174660',
    projectId: 'project-chat-d6cb6',
    storageBucket: 'project-chat-d6cb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdg_OfHDHyX_JgbiBnDuvqxewOdozu3vQ',
    appId: '1:86067174660:ios:59c5c974929e5b01584451',
    messagingSenderId: '86067174660',
    projectId: 'project-chat-d6cb6',
    storageBucket: 'project-chat-d6cb6.appspot.com',
    iosBundleId: 'com.example.tutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdg_OfHDHyX_JgbiBnDuvqxewOdozu3vQ',
    appId: '1:86067174660:ios:f50f07e91b604ec0584451',
    messagingSenderId: '86067174660',
    projectId: 'project-chat-d6cb6',
    storageBucket: 'project-chat-d6cb6.appspot.com',
    iosBundleId: 'com.example.tutorial.RunnerTests',
  );
}
